### ISSUE TITLE
Q/A for 3 issues

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-mstg#1023]
We need to get the Q/A done on the following delta, (to speed up the review process):
https://github.com/OWASP/owasp-mstg/compare/55ade23b765aeb09f945583ddd012db7891969ed...master 

It covers:

- [x] #1019 MASVS 2.12 missing for Android and iOS (in 0x04 section..)
- [x] #1018 Testing the Device-Access-Security Policy is removed for iOS (to be researched) (as a counterpart for confirm credentials for android)
- [x] #1008 Testing Input Validation and Sanitization
- [x] Additionally the last chapter has been extended with a set of vulnerable applications to check/study.

**Comment by commjoen** [comment]
The issues that include in these changes are:
- #1019 MASVS 2.12 missing for Android and iOS (in 0x04 section..) 
- #1018 Testing the Device-Access-Security Policy is removed for iOS (to be researched) (as a counterpart for confirm credentials for android) 
- #1008 Testing Input Validation and Sanitization

Additionally the last chapter has been extended with a set of vulnerable applications to check/study.

**Comment by commjoen** [comment]
Thank you again @TheDauntless ! You rock as a reviewer!
