### ISSUE TITLE
Update for iOS 13 / Android 10

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-mstg#1317]
There are quiet a few security updates for both android Q and iOS 13 which require attention. This ticket is about setting up these new security feature/updates into new tickets.
Android: New location controls and reminder, Privacy settings
- [x] Biometric changes: https://developer.android.com/about/versions/10/features#improved-biometric-auth . #1504
- [x] TLS 1.3 support: https://developer.android.com/about/versions/10/features#tls-1.3 . #1505
- [x] Run DEX directly as an anti-tampering control: https://developer.android.com/about/versions/10/features#embedded-dex. #1506
- [x] Public Conscrypt API: https://developer.android.com/about/versions/10/features#conscrypt . #1505
- [x] Programmatic connectivity management: https://developer.android.com/about/versions/10/features#q-connnectivity . #1507
- [x] Scoped storage changeS: https://developer.android.com/about/versions/10/features#create-files-external-storage . #1508 
- [x] Autofill challenges: https://developer.android.com/about/versions/10/features#updating-datasets . #943
- [x] Webview changes: https://developer.android.com/about/versions/10/features#webview-hung , #1487
- [x] New Foreground service type: https://developer.android.com/about/versions/10/features#fg-service-types . #1509
- [x] NDK changeS: https://developer.android.com/about/versions/10/features#q-ndk . #889

iOS: 
- [x] Cryptokit (#1478)
- [x] Bot detection (is not there yet...)
- [x] iPad app to mac https://developer.apple.com/documentation/uikit/creating_a_mac_version_of_your_ipad_app/ & https://developer.apple.com/ipad-apps-for-mac/ . #1510
- [x] Sign in with apple: https://developer.apple.com/sign-in-with-apple/ .#1511
- [x] Background Tasks: https://developer.apple.com/documentation/backgroundtasks/ . #1512
- [x] Core data sync: https://developer.apple.com/documentation/coredata/mirroring_a_core_data_store_with_cloudkit/ . #1513
- [x] NFC challenges: (Core NFC): https://developer.apple.com/documentation/corenfc/, #1514

**Comment by commjoen** [comment]
iOS 13: https://developer.apple.com/documentation/cryptokit, bot detection, app portability to mac OSX

**Comment by commjoen** [comment]
Will create the other tickets soon 👍

**Comment by commjoen** [comment]
Android: New location controls and reminder, Privacy settings
- [ ] Biometric changes: https://developer.android.com/about/versions/10/features#improved-biometric-auth
- [ ] TLS 1.3 support: https://developer.android.com/about/versions/10/features#tls-1.3
- [ ] Run DEX directly as an anti-tampering control: https://developer.android.com/about/versions/10/features#embedded-dex
- [ ] Public Conscrypt API: https://developer.android.com/about/versions/10/features#conscrypt
- [ ] Programmatic connectivity management: https://developer.android.com/about/versions/10/features#q-connnectivity
- [ ] Scoped storage changeS: https://developer.android.com/about/versions/10/features#create-files-external-storage
- [ ] Autofill challenges: https://developer.android.com/about/versions/10/features#updating-datasets
- [ ] Webview changes: https://developer.android.com/about/versions/10/features#webview-hung
- [ ] New Fporeground service type: https://developer.android.com/about/versions/10/features#fg-service-types
- [ ] NDK changeS: https://developer.android.com/about/versions/10/features#q-ndk


iOS: 
- [ ] Cryptokit (#1478)
- [ ] Bot detection
- [ ] iPad app to mac https://developer.apple.com/documentation/uikit/creating_a_mac_version_of_your_ipad_app/ & https://developer.apple.com/ipad-apps-for-mac/
- [ ] Sign in with apple: https://developer.apple.com/sign-in-with-apple/
- [ ] Background Tasks: https://developer.apple.com/documentation/backgroundtasks/
- [ ] Core data sync: https://developer.apple.com/documentation/coredata/mirroring_a_core_data_store_with_cloudkit/
- [ ] NFC challenges: (Core NFC): https://developer.apple.com/documentation/corenfc/

**Comment by sushi2k** [comment]
Thanks Jeroen, nice overview. Some of the things might touch existing content in the MSTG only slightly (e.g. https://developer.android.com/about/versions/10/features#updating-datasets), but all of them should be issues so we can test/evaluate them.

**Comment by commjoen** [comment]
All issues are created. closing this one.
