### ISSUE TITLE
Hybrid application checklist experiments: 

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-mstg#1482]
This issue covers delta analysis of the 3 most important hybrid platforms:

- [ ] React native: https://drive.google.com/open?id=1P5FZ_Bup5eSPOmkePZA8cIpKGOKvngkN
- [ ] Xamarin: https://drive.google.com/open?id=1UL1yLRREJwXfe0HlrcX-IuvPYQM7lTtG
- [ ] Flutter: https://drive.google.com/open?id=1wHK3VI1cU1xmYrCu9yb5OHKUEeLIPSkC

**Comment by commjoen** [comment]
Work is progressing on the xamarin sheet thanks to spirit. The react native sheet is slowly receiving updates..  flutter is getting no progress...
