### ISSUE TITLE
Create issues due to ios 12 update

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-mstg#911]
As the developer beta is out, it is time to start writing updates regarding the security items in ios 12...
The following items need to get a ticket:

- [x] Update on the network stack: #1160
- [x] Reduced device tracking (only identifier for vendor): #1161
- [x] Strong and unique password integration (including reused password integration in settings) (ASWebAuthenticationSession, AuthenticationServices): #1162
- [x] Security code AutoFill #1162
- [x] Improved password sharing: #1162
- [x] Notification API (e.g.: prevent showing secretive info on a locksscreen) #1163
- [x] Passcode unlock requirement before being able to connect a computer to it (update howto's and add the unlock step) #1164

**Comment by sushi2k** [comment]
We should create issues for each test case that might need an update in iOS, for example like this one https://github.com/OWASP/owasp-mstg/issues/895. 
Let's indicate the source that explains the new security feature/change and also where in the guide this information should be placed.

**Comment by commjoen** [comment]
The following items have changed according to https://developer.apple.com/ios/whats-new/:
- Authentication Services
- Network framework

https://support.apple.com/en-us/HT207459 : SHA1 deprecation

**Comment by commjoen** [comment]
Ready for a first review: is there anything i am missing which is really important?

**Comment by commjoen** [comment]
And check https://corellium.com

**Comment by commjoen** [comment]
All issues have been created which are good to have. we will skip corellium for now as we still do not have access.
